import freezoneImg from "../assets/free_zones.png";
import factoriesImg from "../assets/factories.png";
import localCompaniesImg from "../assets/local_companies.png";
import seaCompaniesImg from "../assets/ships.png";
import carsImg from "../assets/cars_cat3.jpeg";
import civilaircraftImg from "../assets/plan.jpg";
import usersImg from "../assets/users_cat2.webp";
import realEstateImg from "../assets/real_estate.jpg";
import tradersImg from "../assets/seller.jpg";
import deliveryCompaniesImg from "../assets/delivery.jpg";
import { CarType } from "../apis/vehicle/type";
import { RealEstateType } from "../apis/real_estate/type";

const USER_TYPE = {
  LOCAL_COMPANY: "local_company",
  USER: "user",
  FREEZONE: "freezone",
  FACTORY: "factory",
  CAR: "car",
  PLANES: "planes",
  SEA_COMPANIES: "sea_companies",
  NEWS_AGENCY: "news_agency",
  REAL_ESTATE: "real_estate",
  TRADER: "trader",
  DELIVERY_COMPANY: "delivery_company",
};

const categories = [
  { url: freezoneImg, name: "free_zone_companies", type: "freezone" },
  { url: factoriesImg, name: "factories", type: "factory" },
  { url: localCompaniesImg, name: "local_companies", type: "local_company" },
  { url: seaCompaniesImg, name: "sea_companies", type: "sea_companies" },
  { url: carsImg, name: "cars", type: "car" },
  { url: civilaircraftImg, name: "civil_aircraft", type: "planes" },
  { url: usersImg, name: "users", type: "user" },
  { url: realEstateImg, name: "real_estate", type: "real_estate" },
  { url: tradersImg, name: "traders", type: "trader" },
  {
    url: deliveryCompaniesImg,
    name: "delivery_companies",
    type: "delivery_company",
  },
];

const REAL_ESTATE_TYPES: RealEstateType[] = [
  {
    name: "residential",
    categories: [
      "apartment",
      "villa",
      "townhouse",
      "penthouse",
      "residential_building",
      "villa_compound",
      "residential_floor",
    ],
  },
  {
    name: "commercial",
    categories: [
      "office",
      "industrial",
      "retail",
      "staff_accom",
      "shop",
      "warehouse",
      "commercial_floot",
      "commercial_villa",
      "other",
      "bulk_unit",
      "commercial_plot",
      "factory",
      "industrial_land",
      "mixed_use_land",
      "showroom",
      "commercial_building",
    ],
  },
  { name: "rooms", categories: ["apartment", "villa"] },
  { name: "monthly_rent", categories: ["apartment", "villa"] },
  { name: "daily_rent", categories: ["apartment", "villa"] },
];

const SHIP_TYPES: string[] = [
  "cargo ship",
  "passenger ship",
  "fishing ship",
  "tugboat",
  "yacht",
  "sailboat",
  "cruise ship",
];

const CAR_TYPES: CarType[] = [
  { name: "Abarth", categories: ["124", "595", "695", "F595"] },
  {
    name: "Acura",
    categories: ["CSX/EL", "ILX", "MDX", "NSX", "RDX", "RSX/Integra", "TLX"],
  },
  {
    name: "Alfa Romeo",
    categories: [
      "145/146/147",
      "156/159",
      "166",
      "4C",
      "Brera",
      "GIULIETTA",
      "GTV/GT",
      "Giulia",
      "Mito",
      "Spider",
      "Stelvio",
      "Tonale",
    ],
  },
  { name: "Ariel", categories: ["Atom"] },
  {
    name: "Astom Martin",
    categories: [
      "Cygnet",
      "DB10",
      "DB11",
      "DB7",
      "DB9",
      "DBS",
      "Lagonda",
      "One-77",
      "Rapide",
      "Vanquish",
      "Vantage",
      "Virage",
      "Vulcan",
      "Zagato",
    ],
  },
  {
    name: "Audi",
    categories: [
      "A1",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q5",
      "Q7",
      "Q8",
      "R8",
      "RS Q8",
      "RS e-tron",
      "RSQ3",
      "S3/RS3",
      "S4/RS4",
      "S5/RS5",
      "S6/RS6",
      "S7/RS7",
      "S8",
      "TT",
      "e-tron",
    ],
  },
  { name: "BAC", categories: ["Mono"] },
  {
    name: "BAIC",
    categories: [
      "A1",
      "A113",
      "A115",
      "A5",
      "A523",
      "BJ40L",
      "D20",
      "K21",
      "MZ40",
      "MZ45",
      "X35",
      "X424",
      "X7",
    ],
  },
  {
    name: "Bentley",
    categories: [
      "Arnage",
      "Azure",
      "Bentayga",
      "Brooklands",
      "Continental",
      "Continental Flying Spur",
      "Continental GT",
      "Mulsanne",
    ],
  },
  { name: "Bestune", categories: ["B70", "T77", "T99", "X40", "X80"] },
  {
    name: "BMW",
    categories: [
      "1-Series",
      "2-Series",
      "3-Series",
      "4-Series",
      "5-Series",
      "6-Series",
      "7-Series",
      "8-Series",
      "M-Coupe",
      "M-Roadster",
      "M1",
      "M2",
      "M3",
      "M4",
      "M5",
      "M6",
      "M7",
      "M8",
      "M850i",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "XM",
      "Z1",
      "Z3",
      "Z4",
      "Z8",
      "i3",
      "i8",
      "iX",
    ],
  },
  { name: "Borgward", categories: ["BX5", "BX7"] },
  { name: "Brilliance", categories: ["FRV", "HS30", "V5", "V6"] },
  {
    name: "Bugatti",
    categories: [
      "Chiron",
      "Divo",
      "Grand Sport",
      "Grand Sport Vitesse",
      "Super Sport",
      "Veyron",
      "Veyron 16.4",
    ],
  },
  {
    name: "BYD",
    categories: ["F3", "F5", "F6", "F7", "HAN", "Qin Pro", "S6", "Song Pro"],
  },
  {
    name: "Cadillac",
    categories: [
      "ATS",
      "BLS",
      "CT4",
      "CT5",
      "CT6",
      "CTS/Catera",
      "DTS/De Ville",
      "Escalada",
      "Fleetwood",
      "Lyriq",
      "SLS",
      "SRX",
      "STS/Seville",
      "XLR",
      "XT4",
      "XT5",
      "XT6",
      "XTR/Eldorado",
      "XTS",
    ],
  },
  { name: "Can-am", categories: ["Maverick", "Maverick X3"] },
  {
    name: "Caterham",
    categories: [
      "620 R",
      "CSR",
      "Seven 165",
      "Seven 270",
      "Seven 360",
      "Seven 420",
    ],
  },
  { name: "CEVO", categories: ["C"] },
  {
    name: "Changan",
    categories: [
      "Alsvin",
      "Alsvin V7",
      "CS35",
      "CS35 Plus",
      "CS75",
      "CS75 Plus",
      "CS85",
      "CS95",
      "E-Star",
      "Eado",
      "Eado Plus",
      "UNI-K",
      "Uni-T",
      "Uni-v",
    ],
  },
  {
    name: "Chery",
    categories: [
      "A11",
      "Arrizo 3",
      "Arrizo 5",
      "Arrizo 7",
      "B11",
      "E5",
      "E8",
      "QQ",
      "S11",
      "T11",
      "Tiggo 3",
      "Tiggo 4",
      "Tiggo 5",
      "Tiggo 7",
      "Tiggo 8",
      "V5",
    ],
  },
  {
    name: "Chevorlet",
    categories: [
      "Apache",
      "Astro",
      "Avalanche",
      "Aveo",
      "Bel Air",
      "Blazer",
      "Bolt",
      "CSV",
      "Camaro",
      "Caprice",
      "Captiva",
      "Cavalier",
      "Chevelle",
      "Colorado",
      "Corvette",
      "Cruze",
      "Epica",
      "Equinox",
      "Explorer",
      "Express",
      "Groove",
      "HHR",
      "Impala",
      "Lumina",
      "Malibu",
      "Menlo",
      "Monte Carlo",
      "Nova",
      "Optra",
      "Pickup",
      "SSR",
      "Silverado",
      "Sonic",
      "Spark",
      "Suburban",
      "T-Series",
      "Tahoe",
      "Traiblazer",
      "Traverse",
      "Trax",
      "Uplander",
    ],
  },
  {
    name: "Chrysler",
    categories: [
      "200/200C EV",
      "300",
      "300M/300C",
      "Concorde",
      "Crossfire",
      "Neon",
      "PT Cruiser",
      "Pacifica",
      "Prowler",
      "Sebring",
      "Voyager/Caravan",
    ],
  },
  {
    name: "Citroen",
    categories: [
      "AX",
      "Berlingo",
      "C-Elysee",
      "C2",
      "C3",
      "C4",
      "C5",
      "C8",
      "DS 3",
      "DS 4",
      "DS 5",
      "Jumber",
      "Saxo",
      "Traction Avant",
      "Xsara Picasso",
    ],
  },
  { name: "CMC", categories: ["Veryca", "Z7"] },
  {
    name: "Daewoo",
    categories: ["Lanos", "Leganza", "Matiz", "Musso", "Nubira"],
  },
  {
    name: "Daihatsu",
    categories: [
      "Charade",
      "Gran Max",
      "Materia",
      "Rocky",
      "Sirion",
      "Terios",
      "YRV",
    ],
  },
  { name: "Datsun", categories: ["240Z", "280Z", "280ZX", "810"] },
  { name: "DFSK", categories: ["v21"] },
  {
    name: "Dodge",
    categories: [
      "Avenger",
      "Caliber",
      "Caravan",
      "Challenger",
      "Charger",
      "Coronet",
      "Dakota",
      "Dart",
      "Duarango",
      "Journey",
      "Magnum",
      "Neon",
      "Nitro",
      "Pickup",
      "Ram",
      "Stealth",
      "Van",
      "Viper",
    ],
  },
  {
    name: "DongFeng",
    categories: ["DFSK V21", "DFSK V22", "H30 Cross", "S30"],
  },
  {
    name: "Dorcen",
    categories: ["Domy X5", "Domy X7", "G60", "G60S", "G70", "G70S"],
  },
  { name: "Equus", categories: ["Bass 770"] },
  { name: "Faw", categories: ["Oley"] },
  { name: "Fenyr", categories: ["SuperSport"] },
  {
    name: "Ferrari",
    categories: [
      "296 GTB",
      "296 GTS",
      "348",
      "355",
      "360",
      "458",
      "458 Italia",
      "458 Speciale",
      "458 Spider",
      "488",
      "488 GTB",
      "488 Spider",
      "512",
      "599",
      "599 GTB",
      "612 Scaglietti",
      "812 GTS",
      "812 Superfast",
      "California",
      "California T",
      "F12",
      "F430",
      "F430 Spider",
      "F8 Spider",
      "F8 Tributo",
      "FF",
      "Ferrari 456",
      "Ferrari Enzo",
      "GTC4 Lusso",
      "Icona",
      "LaFerrari",
      "Portofino",
      "Purosangue",
      "Roma",
      "SF90 Spider",
      "SF90 Stradale",
      "Scaglietti",
      "Super America",
      "Testarossa",
    ],
  },
  {
    name: "Fiat",
    categories: [
      "124 Spider",
      "500X",
      "Abarth",
      "Barchetta",
      "Brava",
      "Bravo",
      "Ducato",
      "Fiat-500",
      "Fiorino",
      "Fullback",
      "Linea",
      "Marea",
      "Punto",
      "Sienna",
      "Tempra",
      "Uno",
    ],
  },
  { name: "Fiskar", categories: ["Karma"] },
  { name: "Force", categories: ["Traveller"] },
  {
    name: "Ford",
    categories: [
      "Aerostar",
      "Bronco",
      "Crown Victoria",
      "Ecosport",
      "Edge",
      "Escape",
      "Escort",
      "Everest",
      "Excursion",
      "Expedition",
      "Explorer",
      "F-Series Pickup",
      "Fiesta",
      "Figo",
      "Five Hundred",
      "Flex",
      "Focus",
      "Fusion",
      "GT",
      "Mondeo",
      "Mustang",
      "Mustanf Mach-E",
      "Pickup",
      "Ranger",
      "Shelby Cobra",
      "Super Duty",
      "Taurus",
      "Territory",
      "Thunderbird",
      "Torino",
      "Tourneo",
      "Transit",
      "Van",
    ],
  },
  { name: "Foton", categories: ["SUP", "TUALAND", "View"] },
  {
    name: "GAC",
    categories: ["GA3", "GA6", "GA8", "GN6", "GN8", "GS3", "GS4", "GS7", "GS8"],
  },
  {
    name: "GAC Gonow",
    categories: ["Chiller Pickup", "M1/M2", "Mini Buses", "Troy 100/500"],
  },
  {
    name: "Geely",
    categories: [
      "Coolray",
      "Emgrand 7",
      "Emgrand 8",
      "Emgrand GS Sport",
      "Emgrand GT",
      "Emgrand GT V6",
      "Emgrand X7",
      "Emgrand X7 Sport",
      "GC2",
      "GC6",
      "GX2",
    ],
  },
  {
    name: "Genesis",
    categories: ["Coupe", "G70", "G80", "G90", "GV70", "GV80"],
  },
  {
    name: "GMC",
    categories: [
      "Acadia",
      "Canyon",
      "Envoy",
      "Hummer",
      "Jimmy",
      "Pickup",
      "Savana",
      "Sierra",
      "Suburban",
      "Terrain",
      "Yukon",
    ],
  },
  { name: "Grand Tiger", categories: ["Grandtiger Pickup"] },
  {
    name: "Great Wall",
    categories: ["Poer", "Wingle 5", "Wingle 6", "Wingle 7"],
  },
  { name: "Gumpert", categories: ["Apollo", "Explosion"] },
  { name: "Haval", categories: ["Dargo", "H2", "H6", "H8", "H9", "Jolion"] },
  {
    name: "Honda",
    categories: [
      "Accord",
      "CR-V",
      "CR-Z",
      "City",
      "Civic",
      "Crosstour",
      "ENS1",
      "Element",
      "Fit",
      "HR-V",
      "Jazz",
      "Legend",
      "M-NV",
      "MR-V",
      "Odyssey",
      "Odyssey J",
      "Pickup",
      "Pilot",
      "Prelude",
      "S2000",
      "Van",
    ],
  },
  {
    name: "Hongqi",
    categories: ["E-HS9", "H5", "H7", "H9", "HS5", "HS7", "HS9"],
  },
  { name: "Hummer", categories: ["H1", "H2", "H3", "H3T", "HX"] },
  {
    name: "Hyundai",
    categories: [
      "Accent",
      "Atos",
      "Avanti",
      "Azera",
      "Casper",
      "Centennial",
      "Coupe",
      "Creta",
      "Elantra",
      "Entourage",
      "Excel",
      "Galloper",
      "Genesis",
      "Getz",
      "Grand Santa Fe",
      "Grand i10",
      "Grandeur",
      "H 100",
      "H1",
      "loniq",
      "Kona",
      "Matrix",
      "Palisade",
      "Santa Cruz",
      "Santa Fe",
      "Sonata",
      "Staria",
      "Terracan",
      "Tiburon",
      "Trajet",
      "Tucson",
      "Veloster",
      "Venue",
      "Veracruz",
      "Verna",
      "i10",
      "i20",
      "i30",
      "i40",
    ],
  },
  {
    name: "Infinity",
    categories: [
      "EX35",
      "FX45/FX35",
      "FX50",
      "G-Series",
      "G25",
      "G35",
      "G37",
      "I35/I37",
      "J30",
      "JX-Series",
      "M-Series",
      "Q30",
      "Q40",
      "Q45",
      "Q50",
      "Q60",
      "Q70",
      "QX30",
      "QX4",
      "QX50",
      "QX55",
      "QX56",
      "QX60",
      "QX70",
      "QX80",
    ],
  },
  { name: "International", categories: ["CXT", "MXT"] },
  {
    name: "Isuzu",
    categories: [
      "Amigo",
      "Ascender",
      "Axiom",
      "D-Max",
      "I Mark",
      "Impulse",
      "MU-X",
      "Oasis",
      "Rodeo",
      "Stylus",
      "Trooper",
      "i-Series",
    ],
  },
  { name: "Iveco", categories: ["Daily"] },
  {
    name: "JAC",
    categories: [
      "City Bus",
      "HK6730",
      "J4",
      "J5",
      "J6",
      "J7",
      "M1",
      "M5",
      "S3",
      "S7",
      "T6 Pickup",
      "Tourist Bus",
    ],
  },
  {
    name: "Jaguar",
    categories: [
      "E-Pace",
      "E-Type",
      "F-Pace",
      "F-Type",
      "I-Pace",
      "S-Type",
      "X-Type",
      "XE",
      "XF",
      "XJ-Series",
      "XJ12",
      "XJ6",
      "XJ8",
      "XJR",
      "XJS",
      "XK",
      "XK8",
      "XKR",
    ],
  },
  {
    name: "Jeep",
    categories: [
      "Cherokee",
      "Commanche",
      "Commander",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Grand Cherokee L",
      "Grand Wagoneer",
      "Liberty",
      "Patriot",
      "Renegade",
      "Wrangler",
      "Wrangler 4xe",
      "Wrangler Unlimited",
    ],
  },
  { name: "Jetour", categories: ["Dashing", "X70", "X90", "X95"] },
  { name: "Jinbei", categories: ["Cargo Van", "DLX", "H2L Highroof"] },
  { name: "JMC", categories: ["NHR", "NKR"] },
  {
    name: "Kia",
    categories: [
      "Bongo",
      "Cadenza",
      "Carens",
      "Carnival",
      "Cerato",
      "EV6",
      "K3",
      "K5",
      "K8",
      "K900",
      "Koup",
      "Mohava",
      "Niro",
      "Oprius",
      "Optima",
      "Pegas",
      "Picanto",
      "Quoris",
      "Rio",
      "Sedona",
      "Seltos",
      "Sephia",
      "Shuma",
      "Sonet",
      "Sorento",
      "Soul",
      "Spectra",
      "Sportage",
      "Stinger",
      "Telluride",
    ],
  },
  { name: "King Long", categories: ["China Mini Van"] },
  {
    name: "Koenigsegg",
    categories: [
      "Agera",
      "CC Prototype",
      "CC8S",
      "CCGT",
      "CCR",
      "CCX",
      "CCXR",
      "ONE:1",
      "Regera",
    ],
  },
  { name: "KTM", categories: ["X-Bow"] },
  { name: "Lada", categories: ["Other"] },
  {
    name: "Lamborghini",
    categories: [
      "Aventador",
      "Countach",
      "Diablo",
      "Gallardo",
      "Huracan",
      "Murcielago",
      "Urus",
      "Other",
    ],
  },
  {
    name: "Lancia",
    categories: ["Delta", "Musa", "Phedra", "Thesis", "Ypsilon", "FX-Series"],
  },
  {
    name: "Land Rover",
    categories: [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "LR2",
      "LR3",
      "LR4",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
      "Other",
    ],
  },
  { name: "LEVC", categories: ["TX5"] },
  {
    name: "Lexus",
    categories: [
      "CT-Series",
      "ES-Series",
      "GS-Series",
      "Gx 460",
      "GX-Series",
      "IS-C",
      "IS-F",
      "IS-Series",
      "IS300",
      "LC 500",
      "LFA",
      "LM 300",
      "LS-Series",
      "LX-Series",
      "LX600",
      "NX 200t",
      "NX 300",
      "NX 350",
      "NX 350H",
      "NX 450H",
      "RC",
      "RC F",
      "RX-Series",
      "SC-Series",
      "UX 200",
    ],
  },
  {
    name: "Lincoin",
    categories: [
      "Aviator",
      "Continental",
      "Corsair",
      "LS",
      "MKC",
      "MKS",
      "MKT",
      "MKX",
      "MKZ",
      "Nautilus",
      "Navigator",
      "Town Car",
    ],
  },
  {
    name: "Lotus",
    categories: ["Elan", "Elise", "Emira", "Esprit", "Evora", "Exige"],
  },
  { name: "Luxgen", categories: ["7 MPV", "7 SUV", "S5", "U6", "U7 Turbo"] },
  { name: "Mahindra", categories: ["Scorpio Pickup", "XUV 500"] },
  {
    name: "Maserati",
    categories: [
      "4200",
      "Coupe",
      "Ghibli",
      "GranCabrio",
      "GranSport",
      "GranTurismo",
      "Levante",
      "MC12",
      "MC20",
      "Quattroporte",
      "Spyder",
    ],
  },
  { name: "Maxus", categories: ["D90", "G10", "T60", "V80"] },
  { name: "Maybach", categories: ["57", "62", "S500"] },
  {
    name: "Mazda",
    categories: [
      "2",
      "3",
      "323",
      "6",
      "626",
      "929",
      "B-Series",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-7",
      "CX-9",
      "MPV",
      "MX-5",
      "MX-6",
      "Navajo",
      "Pickup",
      "Protege",
      "RX-7",
      "RX-8",
      "Tribute",
    ],
  },
  {
    name: "McLaren",
    categories: [
      "540C",
      "570GT",
      "570S",
      "600LT",
      "650S",
      "675LT",
      "720S",
      "765LT",
      "Artura",
      "Elva",
      "F1",
      "GT",
      "MP4-12C",
      "P1",
      "SLR",
      "Senna",
      "Speedtail",
    ],
  },
  {
    name: "Marcedes-Benz",
    categories: [
      "190",
      "220 SE",
      "240/260/280",
      "300/350/380",
      "400/420",
      "420 SEL",
      "500/560",
      "A-Class",
      "A200",
      "AMG",
      "B-Class",
      "C-Class",
      "C-Class Coupe",
      "C43",
      "CL-Class",
      "CLA",
      "CLC",
      "CLK-Class",
      "CLS 450",
      "CLS-Class",
      "E-Class",
      "E-Class Coupe",
      "EQA",
      "EQB",
      "EQC",
      "EQE",
      "EQG",
      "EQS",
      "G-Class",
      "GL-Class",
      "GLA",
      "GLB",
      "GLC",
      "GLC 63",
      "GLE Coupe",
      "GLE-Class",
      "GLK-Class",
      "GLS-Class",
      "GT",
      "M-Class",
      "R-Class",
      "S-Class",
      "S-Class Coupe",
      "S580e",
      "SEC-Class",
      "SEL-Class",
      "SL-Class",
      "SLC",
      "SLK-Class",
      "SLR",
      "SLS",
      "Sprinter",
      "V-Class",
      "Viano",
      "Vito",
      "X Class",
    ],
  },
  { name: "Mercedes-Maybach", categories: ["S-Class"] },
  {
    name: "Mercury",
    categories: ["Grand Marquis", "Mariner", "Milan", "Montego", "Mountaineer"],
  },
  {
    name: "MG",
    categories: [
      "360",
      "A",
      "B",
      "GS",
      "GT",
      "HS",
      "MG3",
      "MG350",
      "MG5",
      "MG550",
      "MG6",
      "MG750",
      "MGB",
      "One",
      "RX5",
      "RX8",
      "T60",
      "ZS",
    ],
  },
  { name: "Milan", categories: ["Red"] },
  {
    name: "MINI",
    categories: [
      "Clubman",
      "Cooper",
      "Countryman",
      "Coupe",
      "Mayfair",
      "Paceman",
      "Roadster",
    ],
  },
  {
    name: "Mitsubishi",
    categories: [
      "3000GT",
      "ASX",
      "Attrage",
      "Canter",
      "Colt",
      "Diamonte",
      "Eclipse",
      "EclipseCross",
      "Evolution",
      "Fortis",
      "Galant",
      "Grandis",
      "L200",
      "Lancer",
      "Magna",
      "Mirage",
      "Montero",
      "Montero Sport",
      "Nativa",
      "Outlander",
      "Pajero",
      "Pajero Sport",
      "Pickup",
      "Van",
      "Xpander",
      "Xpander Cross",
    ],
  },
  {
    name: "Morgan",
    categories: [
      "3 Wheeler",
      "4 Seater",
      "4/4",
      "Aero 8",
      "Aero Coupe",
      "Aero Supersport",
      "Plus 4",
      "Plus 6",
      "Plus 8",
      "Roadster",
    ],
  },
  { name: "Morris", categories: ["Minor"] },
  { name: "Nio", categories: ["ES6"] },
  {
    name: "Nissan",
    categories: [
      "280ZX",
      "300ZX",
      "350Z",
      "370z",
      "400Z",
      "Altima",
      "Armada",
      "GT-R",
      "Gloria",
      "Juke",
      "Kicks",
      "Leaf",
      "Maxima",
      "Micra",
      "Murano",
      "Navara",
      "Pathfinder",
      "Patrol",
      "Patrol Pickup",
      "Pickup",
      "Primara",
      "Qashqai",
      "Quest",
      "Rogue",
      "S130",
      "Sentra",
      "Silvia",
      "Skyline",
      "Sunny",
      "Sylphy",
      "Terrano",
      "Tiida",
      "Titan",
      "Urvan",
      "Van",
      "Versa",
      "X-Trail",
      "Xterra",
    ],
  },
  { name: "Noble", categories: ["M600"] },
  {
    name: "Opel",
    categories: [
      "Antara",
      "Astra",
      "Cascade",
      "Corsa",
      "Crossland X",
      "Grandland X",
      "Insignia",
      "Kadett",
      "Meriva",
      "Mokka",
      "Omega",
      "Signum",
      "Vectra",
      "Vita",
      "Zafira",
    ],
  },
  { name: "Oullim", categories: ["SPIRRA"] },
  { name: "Pagani", categories: ["Huayra", "Zonda"] },
  { name: "PAL-V", categories: ["Pioneer Limited Edition", "Sport Edition"] },
  {
    name: "Peugeot",
    categories: [
      "2008",
      "2008 GT LINE",
      "206",
      "206cc",
      "207",
      "207cc",
      "208",
      "208 GT LINE",
      "3008",
      "3008 GT LINE",
      "301",
      "307",
      "307cc",
      "308",
      "308 GT LINE",
      "308cc",
      "407",
      "408",
      "5008",
      "5008 GT LINE",
      "504/5",
      "508",
      "607",
      "Boxer",
      "Expert",
      "Partner",
      "RC7",
      "RCZ",
      "Rifter",
      "iOn",
    ],
  },
  { name: "PGO", categories: ["Speedster"] },
  { name: "Polestar", categories: ["1", "2", "3", "4", "6"] },
  { name: "Pontiac", categories: ["Catalina", "Firebird", "GTO", "Trans Am"] },
  {
    name: "Porche",
    categories: [
      "718 Spyder",
      "918 Spyder",
      "928",
      "944",
      "968",
      "Boxster",
      "Carrera / 911",
      "Cayenne",
      "Cayman",
      "Macan",
      "Panamera",
      "Taycan",
    ],
  },
  { name: "Proton", categories: ["Sega", "Savvy", "Waja", "Wira"] },
  { name: "Proton", categories: ["Sega", "Savvy", "Waja", "Wira"] },
  {
    name: "Renault",
    categories: [
      "Capture",
      "Clio",
      "Dokker",
      "Duster",
      "Espace",
      "Fluence",
      "Koleos",
      "Laguna",
      "Logan",
      "Megana",
      "Safrane",
      "Sandero",
      "Scenic",
      "Symbol",
      "Talisman",
      "Trafic",
      "Twingo",
      "Twizy",
      "Zoe",
    ],
  },
  { name: "Rivian", categories: ["R1S", "R1T"] },
  {
    name: "Rolls Royce",
    categories: [
      "Cullinan",
      "Dawn",
      "Ghost",
      "Phantom",
      "Silver Seraph",
      "Silver Shadow",
      "Silver Spur",
      "Wraith",
    ],
  },
  { name: "Rover", categories: ["75"] },
  { name: "Saab", categories: ["9-2x", "9-3", "9-5", "9-7x", "900", "9000"] },
  {
    name: "Seat",
    categories: [
      "Alhambra",
      "Altea",
      "Cordoba",
      "Exeo",
      "Ibiza",
      "Leon",
      "Toledo",
    ],
  },
  { name: "Shenlong/Sunlong", categories: ["SLK 6112", "SLK 6120"] },
  {
    name: "Skoda",
    categories: [
      "Fabia",
      "Kamiq",
      "Karoq",
      "Kodiaq",
      "Kushaq",
      "Octavia",
      "Rapid",
      "Roomster",
      "Scala",
      "Superb",
      "Yeti",
    ],
  },
  { name: "Smart", categories: ["Other"] },
  { name: "Soueast", categories: ["DX3", "DX5", "DX7", "DX8"] },
  { name: "Speranza", categories: ["Other"] },
  { name: "Spyker", categories: ["C8 Preliator"] },
  {
    name: "Subaru",
    categories: [
      "BRZ",
      "Forester",
      "Impreza",
      "Legacy",
      "Outback",
      "Tribeca",
      "WRX",
      "XV",
      "Other",
    ],
  },
  {
    name: "Suzuki",
    categories: [
      "APV Van",
      "Alto",
      "Baleno",
      "Carry",
      "Celerio",
      "Ciaz",
      "Dzire",
      "Ertiga",
      "Grand Vitara",
      "Ignis",
      "Jimny",
      "Kizashi",
      "Liana",
      "SX4",
      "Swift",
      "Vitara",
      "XL7",
      "Other",
    ],
  },
  {
    name: "TATA",
    categories: ["Delivery Truck", "Indigo", "Pickup", "Van", "Zenon", "Other"],
  },
  {
    name: "Tesla",
    categories: ["Model 3", "Model S", "Model X", "Model Y", "Tesla Roadster"],
  },
  {
    name: "Toyota",
    categories: [
      "4Runner",
      "86",
      "Alphard",
      "Aurion",
      "Avalon",
      "Avanza",
      "Avensis",
      "C-HR",
      "Camry",
      "Celica",
      "Corolla",
      "Corolla Cross",
      "Corona",
      "Cressida",
      "Crown",
      "Echo",
      "FJ Cruiser",
      "Fortuner",
      "Granvia",
      "Hiace",
      "Highlander",
      "Hilux",
      "IQ",
      "Innova",
      "Land Cruiser",
      "Land Cruiser 70",
      "Land Cruiser 76 series",
      "MR2",
      "MR2 Spyder",
      "Pickup",
      "Prado",
      "Previa",
      "Prius",
      "Raize",
      "Rav 4",
      "Rush",
      "Scion",
      "Sequoia",
      "Sienna",
      "Supra",
      "Tacoma",
      "Tercel",
      "Tundra",
      "Veloz",
      "Wigo",
      "XA",
      "Yaris",
      "Zelas",
      "iA",
      "Other",
    ],
  },
  {
    name: "UAZ",
    categories: ["Cargo", "Commercial", "Hunter", "New Patriot", "New Pickup"],
  },
  { name: "Victory", categories: ["V1"] },
  {
    name: "Volkswagen",
    categories: [
      "Amarok",
      "Arteon",
      "Beelte",
      "Bora",
      "CC",
      "Caddy",
      "Crafter",
      "E-Lavida",
      "Eos",
      "Eurovan",
      "GTI",
      "Golf",
      "Golf R",
      "ID.3",
      "ID.4",
      "ID.6",
      "Jetta",
      "Multivan",
      "Passat",
      "Phaeton",
      "Polo",
      "Routan",
      "Scirocco",
      "Sharan",
      "T-Roc",
      "TAYRON",
      "Teramount",
      "Tiguan",
      "Touareg",
      "Touran",
      "Transporter",
      "Vento",
      "Viloran",
      "Other",
    ],
  },
  {
    name: "Volvo",
    categories: [
      "C-Class",
      "C40",
      "S-Class",
      "V-Class",
      "V90",
      "XC40",
      "XC60",
      "XC70",
      "XC90",
      "Other",
    ],
  },
  { name: "W Motors", categories: ["Fenyr Hypersport", "Lykan Hypersport"] },
  {
    name: "Westfield Sportscars",
    categories: ["Classic", "Special Edition", "Sport 250", "Track"],
  },
  { name: "Wiesmann", categories: ["MF3", "MF4", "MF5"] },
  { name: "XPeng", categories: ["G9", "P7"] },
  { name: "ZNA", categories: ["Oting", "Rich", "Yumsun"] },
  {
    name: "Zotye",
    categories: ["E200", "T300", "T600", "T600 Sport", "T700", "Z100"],
  },
  { name: "BMW Alpina", categories: ["B3", "B4", "B5", "B6", "B7"] },
  { name: "Exeed", categories: ["LX", "TXL", "VX"] },
  { name: "Fengon", categories: ["500", "580", "600", "IX5", "IX7"] },
  { name: "Lynk & Co", categories: ["01", "05"] },
  {
    name: "Marcedes-AMG",
    categories: [
      "GT",
      "GT Black Series",
      "GT C",
      "GT C Roadster",
      "GT R",
      "GT R Pro",
      "GT S",
    ],
  },
  { name: "Oldsmobile", categories: ["Delta 88"] },
  {
    name: "Other Make",
    categories: [
      "F1",
      "Heavy Vehicles",
      "Other 4x4",
      "Other Car",
      "Other Minivan",
      "Other Pickup",
      "Other Utility",
    ],
  },
  { name: "Qiantu", categories: ["K50"] },
  {
    name: "SsangYong",
    categories: ["Korando", "Kyron", "Musso", "Rexton", "Rodius", "Tivoli"],
  },
  { name: "Studebaker", categories: ["President"] },
  { name: "TANK", categories: ["300", "500"] },
  { name: "Triumph", categories: ["TR4A"] },
  { name: "Voyah", categories: ["Dreamer", "Free"] },
  { name: "Zeekr", categories: ["001", "009"] },
  { name: "Zenvo", categories: ["Aurora", "TSR-S"] },
];

export { categories, USER_TYPE, CAR_TYPES, SHIP_TYPES, REAL_ESTATE_TYPES };
